### PR TITLE
Prerelease for 0.1.1

### PR DESCRIPTION
**Pull request by antfu**
This PR bumps the version to 0.1.1. When I get merged, I will publish it to npm.

----

I think I can help to manage the npm packages since I have access to it. But there are a few things I may want to discuss with you

As I can see currently, we use issues to announce the updates, such as #322 and #399. I would propose trying to add [CHANGELOG.md](https://github.com/olivierlacan/keep-a-changelog) file or using Github Release. To better track the changes.

As for the changelog content, there are people writes it manually and also some people do it fully automatically. I personally use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and [Standard Release](https://github.com/conventional-changelog/standard-version) for most of my projects. But introducing this forces people to write commits messages in some way, which I think it's not necessary for this project in the current stage.

Depends on how you want to do this thing, I can make the pipeline if needed.

### CODE REVIEW

**Comment by LingDong-** [comment]
Thanks @antfu. CHANGELOG sounds great. I also agree that manually writing changes is good enough for now.

**Comment by antfu** [comment]
NPM packages published!

**Comment by antfu** [comment]
@LingDong- Have sent you an email about the changelog things. Please check it out. Thanks!

**Comment by LingDong-** [comment]
@antfu Just replied. Sorry didn't see it earlier.

**Pull request merged**
