### PR TITLE
add an example called 'drawHeart'

### PR DESCRIPTION
**Pull request by BHMulberry**
Draw a heart-shaped pattern with a string parameter. The code is edited by VScode with the support of Anthony Fu's extension. I'm a beginner of both wenyan-lang and js, feel free to improve my code. I would be happy if my first pr was adopted, lol

### CODE REVIEW

**Comment by LingDong-** [comment]
Hi @BHMulberry,

Thank you so much for contributing the example! A couple of things:

- Could you please use the stdlib for `sqrt` and `abs` instead of copying from the toy examples? stdlib implementations are more sophisticated and we would like to promote them :) The syntax is 

```
吾嘗觀「「算經」」之書。方悟「絕對」「平方根」之義。
```

- Small thing: could you please rename the file to `draw_heart.wy` with snake case to conform with the convention of other examples.

- Could you please change 今天天氣不錯 to something more wenyan-ish so it goes with the theme :P

If you are busy at the moment or not sure how to do something, I can merge it and make the changes myself later today.

Thank you very much!

**Comment by BHMulberry** [comment]
Glad to hear from you! 
I’ve made some changes already, which includes:

* Using stdlib `算經` for abs and sqrt functions. Sorry about my careless ignorance of the lib, I didn't even consider about stdlib in wenyan-lang. You've done such a great job! 

* Change the key string from `「「今天天氣不錯」」`to`「「琉璃梳子撫青絲,畫心牽腸癡不癡。」」`. This line came after [溫庭筠](https://en.wikipedia.org/wiki/Wen_Tingyun)'s verse `「「玲珑骰子安红豆，入骨相思知不知」」` by later generations. 

* Rename this example file with snake case. 

Here's the output:
output
It seems that I can do a lot more things with wenyan-lang, and I'll keep doing that. :)

**Comment by BHMulberry** [comment]
@LingDong- 
Also, I've noticed that the test always failed due to the examples are importing stdlib. Why don't you add them in the examples folder or fix the paths? I'm not sure how to do that on github, but we need to pass the test :)

**Comment by LingDong-** [comment]
Awesome, thanks a lot!

The tests are breaking because I recently changed the import mechanism to import platform-specific libraries (e.g. bit ops), and I think it confuses the Gtihub actions. Since @antfu set them up, I'm not sure how to fix it (yet).

@antfu , could you please help with this, thanks :) Otherwise I can investigate too.

**Comment by antfu** [comment]
@LingDong- Sure! Will check it out

**Pull request merged**
