### PR TITLE
Code refactoring in language parser

### PR DESCRIPTION
**Pull request by Madao-3**
## Goal
1. refactor and abstract the parser files.
2. make it have a workflow to add new language
3. some of the py parser code already broke, this pr will fix it too.
4. add missing operator to `py` and `rb` compiler.

## Non-Goal
1. add test cases to all operator is phase 2's goal
2. current `import` bug in ruby and python.

## Phase 2
1. split operator as a component, make it more easier to develop.
2. Fix new syntaxs in ruby and python: `try\catch\catcherr\tryend\throw\import`, currently not working in `master` branch
3. add rust compiler.

### CODE REVIEW

**Comment by antfu** [comment]
I like these changes! But be sure it passes the `make_ide` and `make_site` build. 😉

**Comment by LingDong-** [comment]
Hi @Madao-3 ,

Thanks for helping out. I think your refactoring is a good idea. However, as @antfu mentioned, please make sure you don't break anything. As you might have noticed, there are lot of nuances in the parser code. If you're unsure about anything, please don't hesitate to ask me! In fact, I would prefer to do the refactoring myself, but you've got some good progress. Good luck!

Thank you very much!

**Comment by Madao-3** [comment]
@LingDong- Sure, pass all the test cases is the essential part.
In the next phase, I will try to split all operators as single functions. then we can add unit tests very easily. 😃

**Comment by Madao-3** [comment]
- [ ] site
- [ ] ide
- [ ] npm test

@LingDong- LGTMg

**Comment by Madao-3** [comment]
I think this pr is ready to merge.

**Comment by Madao-3** [comment]
Found a problem, will fix it soon

**Comment by LingDong-** [comment]
Neat 👍! Thank you so much for your great work!
Looking forward to phase 2 :)

**Pull request merged**
