### PR TITLE
fix: stdlib bundling

### PR DESCRIPTION
**Pull request by antfu**
Stdlib is not bundled into npm packages. This PR fixes it.

### CODE REVIEW

**Comment by LingDong-** [comment]
Hmm, all tests are failing. I think the symptom might be indicating that `require` is silently failing (due to `try`), and all the stuff assumed to be imported cannot be found. 🤔

**Comment by antfu** [comment]
@LingDong- Please revert that. Sorry I am on vacation and I didn't bring my laptop with me. Will make another fix on Monday. Sorry for that. Thanks

**Comment by LingDong-** [comment]
No problem at all! Have a great vacation :)

**Comment by antfu** [comment]
Fixed!

**Comment by LingDong-** [comment]
Thanks, and welcome back!

**Pull request merged**
