### PR TITLE
Execute function for core package

### LINKED ISSUE #469: Exec function in core package
## Describe your issue/suggestions

Currently, we only have auto numbers (and bools) conversion to hanzi in online ide. Not in cli, in browser runtime and other interfaces like vscode and sublime plugins.

I propose to extract the functionality and expose it in the core package allowing other interfaces to reuse this feature. This can make it more wenyan-ish without care about the internal details about it.

Meanwhile, this can also solve the floating-point testing issue, #457.

I would love to make a PR for this.

More related issues #465, https://github.com/antfu/wenyan-lang-vscode/issues/12

------

### New function `execute`

Allowing users to directly execute the source code through the API. This will be a simple wrapper of `compile` and `evalCompiled`

```js
function execute (source, options = { hanzinize: true, ...other options in compile })
```

### New function `evalCompiled`

This is basically all the changes happen. It will hijack the console.log and outputs hanzi result when the hanzinize option is set.

```js
function evalCompiled (compiledCode, options = { hanzinize: true })
```

### New CLI options `--hanzinize`

Default to true. Only works for executing mode

### New Browser Runtime script attr `hanzinize`

Default to true.

```html
<script type="application/wenyan" scoped hanzinize="false">
吾有一數。曰三。書之。
</script>
```

## Checklist

Before you create this issue, Please make sure ALL the following items are checked

- [x] If this is a feature request, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

### LINKED ISSUE #471: Proposal for new compile API
## Describe your issue/suggestions

Current `compile` API
```js
function compile(targetLanguage, source, options)
```

Proposed API

```js
function compile(source, options)

options = {
  lang: 'js' // by default
  ...other options
}
```

## Checklist

Before you create this issue, Please make sure ALL the following items are checked

- [x] If this is a feature request, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

### PR DESCRIPTION
**Pull request by antfu**
This resolves #469, resolves #471 

## Progress
- [x] `evalCompiled` function 
- [x] `execute` function 
- [x] `compile` api changes with backward compatibly, #471
- [x] works for CLI
- [x] works for `ide` `site`
- [x] works for unit test
- [x] works for browser runtime
- [x] option `outputHanzi` for CLI
- [x] option `Ouput Hanzi` for ide
- [x] option `outputHanzi` for runtime
- [x] Update docs

### CODE REVIEW

**Comment by haoger-66** [comment]
能不能给我分享更多有趣的东西

**Comment by antfu** [comment]
It's done. I did a rough test for everything. Hope I didn't break them.

----

For array output, I use `。` for the separators as you did for site. But I am wondering if we should add a prefix and suffix for that in case we have nested array or more complex formats.

```js
function hanzinize(value) {
  if (typeof value == "number") {
    return num2hanzi(value);
  } else if (typeof value == "boolean") {
    return bool2hanzi(value);
  } else if (Array.isArray(value)) {
    return value.map(i => hanzinize(i)).join("。");
  } else {
    return value;
  }
}
```

**Comment by LingDong-** [comment]
Nice, thanks a lot!

For nested structures, I had one idea is to use indentation so we don't introduce extra symbols. But then I did some experimentation on how I would use that to express various structures, and found it ambiguous & problematic. So symbols are probably the way to go. e.g.

```
[0,{a:[1,2,3],b:4},5,6]

《零。《「甲」、《一。二。三》。「乙」、四》。五。六。》
```

My plan is to add this JSON.stringify-like functionality to the standard library 格物經. Discussion welcome!

**Comment by antfu** [comment]
> My plan is to add this JSON.stringify-like functionality to the standard library 格物經

Sounds very promising! If we could port num2hanzi in Wenyan natively, then maybe we could have two different `書之`. One outputs raw data and one outputs hanzi. I think this would open more possibilities for usage.

**Pull request merged**
