### PR TITLE
Add quine example (self-replicating code)

### PR DESCRIPTION
**Pull request by woodrush**
A [quine](https://en.wikipedia.org/wiki/Quine_(computing)) is a program that outputs its own source code. When you input `./examples/quine.wy` in the interpreter, it prints _exactly_ the same string as its original source code.

This commit adds a quine program that I've written in wenyan-lang.

The original idea of the implementation, that quines in JavaScript can be implemented via replacement of strings, is referenced from a code in [this post](https://qiita.com/amoO_O/items/5d0c4edfc99f64bea6fb) by @amo12937 . I've mentioned the URL of this post inside the source code.

### CODE REVIEW

**Comment by woodrush** [comment]
One large room of improvement that can be made on this code is that it explicitly states `String.fromCharCode` inside the source code. This problem can be fixed straightforwardly by implementing #84 .

**Comment by woodrush** [comment]
> ... it prints exactly the same string as its original source code.

Just for clarity, the code doesn't output the comment at the top.

**Comment by LingDong-** [comment]
Wow!! Thanks so much! I always wanted a quine example, but how to make one was beyond me ;)

**Comment by woodrush** [comment]
Thanks for the merge! You're welcome! ;) It was fun writing it in this language. I especially like the rendering of the script, thanks for the cool project!

**Pull request merged**
