### PR TITLE
添加繁体中文的README

### PR DESCRIPTION
**Pull request by Z-fly**
方便港澳台等使用繁体字的人士使用。

### CODE REVIEW

**Comment by antfu** [comment]
Hi. IMHO, for the file naming, I would recommend using `README.zh-CN.md` and `README.zh-TW.md` in order to fit the [BCP 47](https://tools.ietf.org/html/bcp47) convention.

**Comment by Z-fly** [comment]
> Hi. IMHO, for the file naming, I would recommend using `README.zh-CN.md` and `README.zh-TW.md` in order to fit the [BCP 47](https://tools.ietf.org/html/bcp47) convention.

@antfu Now I have renamed those files.

**Comment by LingDong-** [comment]
Thanks a lot!

**Comment by Purstal** [comment]
Hi.
IMO, `zh-Hans` and `zh-Hant` are more suitable language tags, since their differences are about [scripts](https://tools.ietf.org/html/bcp47#section-2.2.3), not [regions](https://tools.ietf.org/html/bcp47#section-2.2.4).

**Comment by antfu** [comment]
@Purstal I agree. Thanks for pointing out!

**Comment by Purstal** [comment]
@antfu You are welcome!

However, Due to poor Internet connection, I failed to clone the repository, so I can't make a pull request on this now😅

**Comment by antfu** [comment]
@Purstal I can make a PR then, thanks!

**Pull request merged**
