### PR TITLE
stdlib: Improve sin, cos and tan (*/1/3)

### PR DESCRIPTION
**Pull request by statementreply**
Robust: 2<sup>*</sup>/4 (Does it work for all input values?)
Accurate: 1/4 (How accurate is the result?)
Well behaved: 3/4 (Does it preserve math properties?)

<sup>*</sup> They technically work for all input values. But for very large input, the loss of accuracy makes them practically useless.

The result could be severely inaccurate either when the angle is very large, or when the angle is very close to a multiple of pi/2.

### CODE REVIEW

**Comment by LingDong-** [comment]
Great, thanks! These math are starting to get too complex for me to comprehend, but I'm going to trust you since you seem to be very good at it :)

@antfu I'm wondering if you could please update the tests? They're probably failing because the results are (hopefully) more accurate. I recall that the floating point results are different on different OS's, hence updating tests on my laptop will probably fail Github?

Thanks!

**Comment by antfu** [comment]
Sure. I will have a look tomorrow and probably trying to find out a way to solve the floating number output precision problem.

Happy New Year btw!

**Comment by statementreply** [comment]
The failing test is `施「餘弦」於「圓周率」。書之。` due to improved accuracy of 餘弦. I've updated the test snapshot.

**Comment by LingDong-** [comment]
thanks and happy new year everyone

**Pull request merged**
