### PR TITLE
ide auto highlight

### PR DESCRIPTION
**Pull request by simon300000**
This adds a 'auto highlight' function to online ide,
Currently it highlight right away for length < 1500,
For code length bigger than 1500, highlightCode will kinda debounce (length/2)ms, which avoid freeze.

(I was writing a script but it freeze the editor when I click run, because there is a loop with some mistake. and when I copy code from readme, there will be styles come with, which cause the code to look strange/hard to read)

### CODE REVIEW

**Comment by simon300000** [comment]
there is a bug

**Comment by simon300000** [comment]
It seems like highlight after return key behave weirdly, So I ignored input with inputType `insertParagraph`

**Comment by langyo** [comment]
mhmmmmmmmmm

i want to make it pretter, and i will use this library: https://github.com/zhui-team/zhui

so i want to ask your advice(also for the repository's author? :P)

**Comment by LingDong-** [comment]
Hi @simon300000,

Thanks so much for the pull request. In fact I myself tried to make the highlighting automatic using `setInterval`, but was plagued by race condition with the system's pinyin input method that causes half-entered pinyin to appear. I see that you're capturing input events, that's probably much better than my method! Thanks! I'll try it out.

Hi @langyo,
I agree we can use a more sophisticated online IDE, and this library seems pretty decent. However, I think this would be a separate project that deserves its own repo. I imagine quite a lot of pieces are needed for a good IDE, and I don't want it to squeeze all of that in a subfolder. If you could start a separate repo, I can put a link to it in the README, and that would be perfect! Thanks!

**Comment by langyo** [comment]
> Hi @simon300000,
> 
> Thanks so much for the pull request. In fact I myself tried to make the highlighting automatic using `setInterval`, but was plagued by race condition with the system's pinyin input method that causes half-entered pinyin to appear. I see that you're capturing input events, that's probably much better than my method! Thanks! I'll try it out.
> 
> Hi @langyo,
> I agree we can use a more sophisticated online IDE, and this library seems pretty decent. However, I think this would be a separate project that deserves its own repo. I imagine quite a lot of pieces are needed for a good IDE, and I don't want it to squeeze all of that in a subfolder. If you could start a separate repo, I can put a link to it in the README, and that would be perfect! Thanks!

Thanks for your reply. You are right that the more sophisticated online IDE should in a dependent repo. I will send a merge request to this project when it has been completed.

**Pull request merged**
