### PR TITLE
add pythagoras_theorem.wy

### PR DESCRIPTION
**Pull request by MerakDipper**
亦称勾股定理

### CODE REVIEW

**Comment by LingDong-** [comment]
Hi @MerakDipper , thanks for the new example!
However, I think `勾股求弦` already has a (more sophisticated) implementation in the standard library `算經`. (https://github.com/LingDong-/wenyan-lang/blob/master/lib/%E7%AE%97%E7%B6%93.wy#L746)
Is there a particular reason you think it would be necessary to add this version?
Thanks!

**Comment by MerakDipper** [comment]
@LingDong- my bad, I didn't realize it already existed. I did a search on "勾股" but github didn't return me anything code. 

My intention was to add more examples that people with less programming/algorithm knowledge but more literature knowledge （with basic mathematical understanding maybe)  can relate to. Similarly I was about to create an example of 贾宪三角（杨辉三角 ）. Could you let me know if that's also implemented here?

Thanks for replying.

**Comment by LingDong-** [comment]
Hi @MerakDipper , I don't think pascal's triangle is in there yet, feel free to add that. In fact, examples in ancient math textbooks are most welcome!
Thanks!

**Comment by MerakDipper** [comment]
closing per discussion above

**Pull request closed without merging**
