### PR TITLE
Auto generate examples README.md by nodejs.

### PR DESCRIPTION
**Pull request by cuixiping**
Auto generate examples README.md by nodejs.
And make examples README.md pretier.
And add some latest examples to list.

### CODE REVIEW

**Comment by antfu** [comment]
I am wondering why don't we consider just rename the examples to Chinese characters especially we are already using them in stdlib?

**Comment by cuixiping** [comment]
> I am wondering why don't we consider just rename the examples to Chinese characters especially we are already using them in stdlib?

I agree.

**Comment by LingDong-** [comment]
Nice script. Thanks @cuixiping 

I think we can keep the English example names for now. 
- The English names relates to names of "typical" examples (helloworld, quine, fizzbuzz etc.) for many languages. I think the examples/IDE serves as a doorway for people coming from other languages, and it's nice to have some familiarity.
- It makes jumping between examples easier in the IDE. For me, I usually click on the `<select>` and type the first few letters of the name of the example, and that example get's highlighted and I simply press Enter to jump to the example. Oftentimes I find myself checking multiple examples simultaneously, so this is invaluable.

Of course, we can change the filenames to Chinese, and then write a table that maps them to English, etc. etc. We can write a new GUI element to search the examples, etc. etc.. But I think we can better utilize our time making more meaningful progress :)

**Comment by cuixiping** [comment]
Can we rename them to English with Chinese? 
For example **`helloworld-問天地好在.wy`**

**Comment by cuixiping** [comment]
I tried rename them to English with Chinese locally. It looks like this.
How do you think about this?

image

image

**Comment by LingDong-** [comment]
Hi @cuixiping ,
Thanks for trying it out. However I'm afraid I don't like it, I think it just adds redundancy to the filenames. If we do this, whenever we want to refer to an example, we need to type both the English and the Chinese name, switching input method halfway. Filename are just identifiers that distinguish the files from one another. There's no need to be comprehensive. `名者實之賓也` :P
Thanks!

**Comment by cuixiping** [comment]
OK. I understand. English filename is simple and easy enough.

**Pull request merged**
