### PR TITLE
Math library (1/N)

### PR DESCRIPTION
**Pull request by statementreply**
This is part 1/N of math library implementation.

## Goals
- [x] math constants
- [x] floating point limits (internal use)
- [x] extended precision arithmetic (internal use)
- [x] abs
- [ ] signbit, copysign (currently not implementable)
- [x] scaleb, logb
- [x] trunc, floor, ceil, round
- [x] sqrt
- [x] hypot

## Not This PR
- exp
- log
- pow
- reduction by 2π (internal use)
- sin, cos, tan
- asin, acos, atan, atan2
- sinh, cosh, tanh
- asinh, acosh, atanh

## Non-Goals
- fma
- correctly rounded sqrt

### CODE REVIEW

**Comment by LingDong-** [comment]
@statementreply Cool, today I just implemented:

```
pow, sin, cos, tan, asin, acos, atan, atan2, hypot, exp, sqrt, log 
```

IMPORTANT: Let's make sure we don't implement the same things twice and waste effort :)
But feel free to take a look at my implementation and point out any errors!

Thanks!

**Comment by statementreply** [comment]
@LingDong- Now that all existing 算經 functions are implemented in wenyan, I'm going to focus on:
- Fix "urgent" bugs: crash and infinite loop.
- Improve accuracy: perhaps not as good as typical libm, but reasonably accurate for e.g. scientific calculator.
- Make it "just work": take care of non-obvious corner cases, so that the average programmers get what they expect and forget about their existence.
- Implement more functionality.

**Comment by statementreply** [comment]
@LingDong- This part is ready.

**Comment by LingDong-** [comment]
@statementreply Wow, you have some very sophisticated implementations! Thank you so much for your great work. 👍

**Pull request merged**
