### PR TITLE
Better ide/site build

### PR DESCRIPTION
**Pull request by antfu**
Sorry to break the current workflow but I think this will benefit in the long term. Please kindly consider this.

## Changes
- Extract html, css, js from `make_ide` and `make_site` to `static`
- `npm run build:site` is now the replacement for `npm run make_ide` and `npm run make_site`
- use webpack to bundle site scripts instead of `catsrc`
- Github Pages may not work

## Benefits
- compiled files will not be included in the repo source (keep the repo clean)
- better management of html css js (and syntax highlight for dev)
- `require` will be bundled correctly, no need to use `try {...} catch {...}` now
- able to use Netlify, no more manual build
- improve the maintainability for future changes

------

If you would like to give [Netlify](https://www.netlify.com/) a try, here is how (Neltify is free for one user only, sorry I can not do it for you)

1. Create an account and link to Github

image

2. Setup the build command and it's good to go

image

3. It will give you a random name for the site, you can change it in the settings
image

4. or if you want to bind your custom domain:
image

----

Here is the demo I created in Netlify on this branch

Site:
https://wenyan-lang-antfu.netlify.com/

IDE:
https://wenyan-lang-antfu.netlify.com/ide

### CODE REVIEW

**Comment by LingDong-** [comment]
I guess you're correct, it's time to do the right thing ;) Plus, we can take the opportunity to migrate to wy-lang.org. 
I'll setup netlify today.
I think it might be a good idea to still have placeholder html's in `/site` that simply do a redirect. e.g. 
```html
<script>window.location.href="http://wy-lang.org"</script>
```
Thanks!

**Comment by antfu** [comment]
@LingDong- Great! I also added [a meta tag for redirecting](https://www.w3docs.com/snippets/html/how-to-redirect-a-web-page-in-html.html).

```html
<head>
  <meta http-equiv="Refresh" content="0; url=http://wy-lang.org"/>
  <script type="text/javascript">
    window.location.href="http://wy-lang.org"
  </script>
</head>
<body>
  <p>Please visit <a href="http://wy-lang.org">http://wy-lang.org</a> instead.</p>
</body>
```

**Comment by LingDong-** [comment]
Just migrated to netlify and wy-lang.org. Everything seems to be working :D Let me know if I missed anything.

**Comment by antfu** [comment]
LGTM👍

A side note, you if are interested enabling https, Netlify can do it by very simple setups. Just under settings>domain management>https.😆

**Comment by LingDong-** [comment]
@antfu Just checked, and I think https is already enabled. Didn't notice before. I'll change the readme to reflect that. Thanks!

**Pull request merged**
