### PR TITLE
Add pascal triangle to example

### PR DESCRIPTION
**Pull request by MerakDipper**
Test Result:
一
一。一
一。二。一
一。三。三。一
一。四。六。四。一
一。五。一十。一十。五。一
一。六。一十五。二十。一十五。六。一
一。七。二十一。三十五。三十五。二十一。七。一
一。八。二十八。五十六。七十。五十六。二十八。八。一
Please kindly let me know:
- if there's better coding style
- if I should be using "杨辉三角" as opposed to "贾宪三角" for awareness

### CODE REVIEW

**Comment by LingDong-** [comment]
Nice, thanks for the new example!

- 賈憲三角 is fine, we should insist on the right credit :)
- Your coding style is good

One request though, could you make it print so that the overall shape is an equilateral triangle instead of a right angle one, like this image: https://upload.wikimedia.org/wikipedia/commons/c/c0/Jiaxian.jpg ? Current is also fine if you don't want to change or think it will over-complicate the code.

Thanks!

**Comment by MerakDipper** [comment]
@LingDong- Good suggestion. I tried to add the padding after you brought up, but right now all the implementations I can think of are very verbose and take away the main point here. I think it might be easier to come back after we have array.toString() method (then we just have to pad spaces). Or let me know if you have an easy implementation in mind.

噫。吾嘗思文言之難，方悟python之易！ :)

**Comment by LingDong-** [comment]
Makes sense. I'll merge it now, and perhaps if later I have time I can see if there's an easy implementation for padding.
Thanks again for the example!

**Comment by MerakDipper** [comment]
@LingDong- thanks. We can keep thinking about it. Let me know if you have some scheme and I can write it out as well.

**Pull request merged**
