### PR TITLE
NPM Packages

### PR DESCRIPTION
**Pull request by antfu**
This continues #241

This PR publishes npm packages under [`@wenyanlang`](https://www.npmjs.com/search?q=%40wenyanlang) scope which I access to. I have invited you to the organization.

For now, this project is published by 4 packages
- @wenyanlang/core - *Exposes the src/parser.js file*
- @wenyanlang/render - *Exposes the src/render.js file*
- @wenyanlang/highlighter - *Exposes the src/highlight.js file*
- @wenyanlang/cli - *Exposes the src/cli.js file, can be installed by `npm i -g @wenyanlang/cli`*

### Changes
- Added a publish scripts that build and publish these packages automatically. It will be called by Github Actions on new releases. Or you can manually publish by `npm run publish`
- Since we have published the packages, scripts can be accessed by using [unpkg](https://unpkg.com/). I have change make_ide and make_site from embedding code to import online scripts.
```diff
+ <script src="https://unpkg.com/@wenyanlang/core/index.min.js"></script>
+ <script src="https://unpkg.com/@wenyanlang/highlighter/index.min.js"></script>
```
- Bundled standard library into @wenyanlang/core
- Make `reader` of @wenyanlang/core not do anything by default since `fs` can not be bundled to browser
- `npm run make_cmdline` is removed. use `npm run build` instead.
- @wenyanlang/core on browser-side will be exported as `window.Wenyan`
```js
Wenyan.compile(...)
```

### CODE REVIEW

**Comment by antfu** [comment]
That's weird. The test passed on my machine but not the CI...

**Comment by LingDong-** [comment]
Hi, let me first roll back to before the pull request.

First, an issue:
- On site, all the highlight colors are wrong, possibly due to scoping, possibly because setting DEFAULT_COLORS no longer work because it is wrapped in some Wenyan.highlighter etc.

A suggestion:
- I don't feel the meta.js file is necessary. Each file has its own constants that are related to what it does. There is no need to grab that out and put it in a same file where things are not apparently related to each other. Unless there is some technical reason?
- And fsReader.js too, it seems to be only used by the parser.

Some questions:

- How do I publish to NPM? do I need to make a release every time? You changed the site to link scripts from NPM, which means that everytime I make a small fix to parser etc. I need to publish to NPM?
- what is `require.context`? I did npm install but it still not recognized. 
- You removed `make_cmdline.js`. I understand we're now just using `src/cli.js` and using `pkg` to build the CLI? How does it handle the standard library, does it copy all the standard library into the binary?

**Comment by antfu** [comment]
> Hi, let me first roll back to before the pull request.

Sure. Thanks! I will fix the issue before we merging.

> On site, all the highlight colors are wrong, possibly due to scoping, possibly because setting DEFAULT_COLORS no longer work because it is wrapped in some Wenyan.highlighter etc.

Will look deep and try to fix that.

> And fsReader.js too, it seems to be only used by the parser.

It's a temporary workaround. Since the `fs` is not available in the browser, I am trying to make the `core` package universal to both node and browser environments. I have seen your implementation for ide and site. But ask every user who tries to run the compiler on the browser to specify the reader seems not a very good approach. I will make some changes and that discusses the detail later

> I don't feel the meta.js file is necessary. Each file has its own constants that are related to what it does. There is no need to grab that out and put it in a same file where things are not apparently related to each other. Unless there is some technical reason?

That's because things like `NUMBER_KEYWORDS` `KEYWORDS` are used in `parser` `render` `highlight`. Let's speak for `highlight`, it only needs these two variables from `parser`, but requiring it will make the bundle contains many other codes of the parser that aren't using by `highlight`. Introducing meta.js can make the bundle more decoupling from others. As for `BOOK_COLORS`, I think I put it in the wrong place, will fix that.

> How do I publish to NPM? do I need to make a release every time?

You can run `npm run publish` on your machine to publish without making a release. I am still learning Github Actions and will optimize the workflow when I found out a better way.

> You changed the site to link scripts from NPM, which means that every time I make a small fix to parser etc. I need to publish to NPM.

Technically, yes. But you don't have to build ide and site every time since they will fetch the latest version of npm. Only build them when you change the HTML or embedded js. But this really depends on you, if you prefer the previous workflow better, I would love to revert it.

> what is require.context?

`require.context` this [a feature of webpack](https://webpack.js.org/guides/dependency-management/). It searches for standard lib and requires them as an object.

> what is require.context? I did npm install but it still not recognized.

Do you mean it can not be recognized by your text editor that or something?

> How does it handle the standard library, does it copy all the standard library into the binary?

Yes. On the browser, it's also exposed to `Wenyan.STDLIB`
image

Hope I have answered your question. I will make changes according to your suggestions. Thanks!

**Comment by antfu** [comment]
I have pushed some fixes.

- The site color highlight is fixed.
- Remove and inlined `fsReader`
- Move `BOOK_COLORS` from `meta` back to `render`
- Tests are passed

For the meta part, I think we can have a better name for it (poor my vocabulary😢).

**Comment by LingDong-** [comment]
Hi @antfu, thank you so much for your work!

Finally seems to work. I made a mistake and bumped the version by 0.01 and now it's 0.02, but otherwise it seems to be working fine!

- How can I quickly test the commandline tool? Do I read to re-install it from NPM each time?

- I think meta can simply be called keywords. Since it's really just, well, keywords. I can do the renaming - the webpack/whatever is going to figure out what files I `require`d and grab those automatically, is that correct? 

- Do you think we need to make the highlighter public? I think most people will just use their own IDE to show the colors with a syntax file, like you did for VSCode. My highlighter is kinda crude and just put every single character in a `<div style="color:">` to give it color.

Sorry for so many questions. Thanks!

**Comment by LingDong-** [comment]
Hmm.. It seems that I can only publish once for every version number?

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@wenyanlang%2fcli - You cannot publish over the previously published versions: 0.0.2.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-12-21T22_31_39_399Z-debug.log

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Publish (/Users/admin/proj/wenyan-lang/tools/publish.js:67:5)
    at /Users/admin/proj/wenyan-lang/tools/publish.js:77:9
(node:51445) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:51445) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LingDong-** [comment]
Seems that one cannot overwrite previously published versions

https://github.com/npm/npm/issues/8305

How about this: we only publish the command line tool, which is for the users, and for our own stuff, let's use my old method which simply dumps all the source code in an HTML automatically. Plus, the page loads faster this way.

**Comment by antfu** [comment]
Sorry for the delay, I just woke up...

> How can I quickly test the commandline tool? Do I read to re-install it from NPM each time?

There is a continue building mode `npm run dev`. It will automatically watch the changes you made and rebuild. Which is also faster than the normal building.

> the webpack/whatever is going to figure out what files I required and grab those automatically, is that correct?

Yes.

> Do you think we need to make the highlighter public? I think most people will just use their own IDE to show the colors with a syntax file, like you did for VSCode. My highlighter is kinda crude and just put every single character in a <div style="color:"> to give it color.

It's just for the ide/site now. I am not sure what user usages would be like in the future. Since you rolled back to the previous method for ide/site. I think you could unpublish it if you want. `npm run unpublish @wenyanlang/highlighter`. If so, I can also remove the build script for it.

> Seems that one cannot overwrite previously published versions

Yes. It's by design of npm. Every version should keep the consistency to make sure all the dependents work. If you think the bumping version is annoying, I can update the script to prompt version number every time before you publish.

> Now I renamed meta to keywords, and brought back the previous workflow for the webpages. I think we should still publish to npm (CLI, core, etc.), but only for other people to use, at least in the current stage of development.

Sure. Do whatever makes you feel better. Sorry for bringing too much complicity to it.

Thanks.

**Comment by LingDong-** [comment]
Thanks so much for the detailed explanation! :)

**Pull request merged**
