### PR TITLE
Test-suites

### PR DESCRIPTION
**Pull request by antfu**
Changes:
- Installed Mocha as a dependence
- Reorganized the test files
- Added scripts in `package.json` for testing
- Removed the Testing section in README since the installation is no longer needed
- Runs tests in Github Actions
- Rewrited `test_parser.js` and supports snapshot testing
- Added [a Doc for explaining the snapshot testing](https://github.com/LingDong-/wenyan-lang/blob/d0969a66c5784793939045c012c7eaa3e778aab3/documentation/Testing.md)

Also, I have found some compiler bugs during the testing. I would open another issue/PR about them.

### CODE REVIEW

**Comment by LingDong-** [comment]
Thanks so much for all these improvements!

**Comment by LingDong-** [comment]
Hi @antfu, could you please change the testing procedure a little bit, so that either `resetVarCnt` option is on for `parser.compile` OR that we only test the output not the compiled js?
I added some code and a new example for it, which cause it generated temporary variable names to be different, causing all tests after that example to fail. :(
Sorry I'm not familiar with the testing, but I'll learn it very soon.
Thank you very much!

**Comment by antfu** [comment]
@LingDong- The test we used, for example, is called snapshot testing. Basically it makes sure your output is matched with last time you believe it's right. It can be helpful to prevent you from being accidentally affected the codes that you make not want to break.

For changes you made on purpose for the compiler or the example code the test will be failed either. In this case, you need to update the snapshot by running `npm run test:update`.

I have included [a Doc for explaining the snapshot testing](https://github.com/LingDong-/wenyan-lang/blob/d0969a66c5784793939045c012c7eaa3e778aab3/documentation/Testing.md) in this PR. Please check it out when you got time. If there is anything unclear, feel free to tell me. Thanks!

**Comment by antfu** [comment]
> we only test the output not the compiled js?

Yeah, that's reasonable. I will make another PR!

**Comment by LingDong-** [comment]
Hi @antfu, yes please. The main reason is that the temporary variable names in the compiled JS are generated like so:

```
var _ans15 = 3; console.log(_ans15);
```

The next time the code is ran, it might generate something like this:

```
var _ans29 = 3; console.log(_ans29);
```

While these are functionally equivalent, the snapshot test fails.

Thank you!

**Pull request merged**
