### PR TITLE
fix: fixed a triffle example grammar error

### PR DESCRIPTION
**Pull request by zxch3n**
Add a "曰" before "「「」」".

The grammar error in this example causes my reverse parser's test failed

### CODE REVIEW

**Comment by LingDong-** [comment]
Hi, thanks for pointing out.

This example is a [quine](https://en.wikipedia.org/wiki/Quine_(computing)), meaning that its output needs to look exactly same as the program itself.

Unfortunately with your additional character it no longer qualifies as a quine. @woodrush wrote this magical thing and I have no idea how to fix it. Perhaps you need to look into the long string literal and add that 曰 there.

Also, I think you don't need to worry too much about testing your reverse parser agianst `quine` and `quine2`. They're really cool but also quite unconventional and use some hacks to work.

Please see if you can make it quine agian :) I'll gladly accept your PR then. Thank you very much!

**Comment by zxch3n** [comment]
Oh, sorry, I forget that! Thanks for your patient explanation.

**Comment by LingDong-** [comment]
Looks good. Thanks a lot!

**Comment by zxch3n** [comment]
NP 😁

**Pull request merged**
