### PR TITLE
Add a summary for examples

### PR DESCRIPTION
**Pull request by cuixiping**
It seems that only `*.wy` files can be in this directory.
I want to add a README.md so we can know the examples more.

### CODE REVIEW

**Comment by cuixiping** [comment]
Failed with message:
`Error: ENOENT: no such file or directory, open '/home/runner/work/wenyan-lang/wenyan-lang/examples/README.wy'`

I think the test script should ignore non-*.wy files.

**Comment by LingDong-** [comment]
Hi @cuixiping , thank you so much for making the summary!

Can you put the README file in `./documentation` folder like `./documentation/EXAMPLE.md` instead? The `example` folder is read automatically and the `.md` files are causing our tests to fail.

Technically we can add an extension filter every time we read the example folder in code, but I think it would be nicer if all the documentation goes into one place. I can add a link to it in the main README to make it more visible. How does that sound?

Thanks!

**Comment by cuixiping** [comment]
If we put the README.md file in ./documentation, the summary content cannot present automatically once we enter this examples directory.

**Comment by LingDong-** [comment]
Hi, what I was saying is that we put a link to the `documentation/EXAMPLES.md` in the readme, so presumably users will be able to know its existence before following the link to the `./examples` folder. The documentation folder already has a lot of docs of similar nature in there, and I think EXAMPLE.md would fit :)

If you really want to have it in `./examples` folder. Please fix the tests/checks. I think you'll need to change `runAll` in `test/examples.test.js`, and `prgms` in `tools/make_site.js` so that they filters out non-`.wy` files.

Thank you very much for your help and understanding!

**Comment by cuixiping** [comment]
I will take a try. Thank you.

**Comment by antfu** [comment]
How about we just change the name of examples to hanzi? The stdlib is already in hanzi. Making examples to hanzi can also be imported by other scripts in a better form.

**Comment by cuixiping** [comment]
Tests passed, you can take a review. I didn't add `documentation/EXAMPLES.md` yet. I can write one if necessary.

**Comment by LingDong-** [comment]
Awesome! Thank you so much!

**Pull request merged**
